### ISSUE TITLE
New update crashes.

### ISSUE THREAD

**Issue by jetnn** [MerlionRock/RealAndroidBot#72]
20:26:10.112 INFO    | Failed to load SSL library: <class 'OSError'> (no library called "ssl" found)
20:26:10.114 INFO    | cryptg module not installed and libssl not found, falling back to (slower) Python encryption
20:26:14.640 ERROR   | RAB is unable to detect any phone attached to your system.
Traceback (most recent call last):
  File "D:\Games\RAB_1_11_0_FULL\RAB\rab.pye", line 355, in setup
    Y\6G=?U19Wqrb<kJU%uE_N^(+9dgD6Il%&<
  File "D:\Games\RAB_1_11_0_FULL\RAB\pokemonlib.pye", line 155, in get_device
    D\LCDqQpG73mpXkLM?g>U<kiC];UDP
pokemonlib.PhoneNotConnectedError

**Comment by bns34** [comment]
Same error
